### ISSUE TITLE
przycisk, który zwiększa wyświetlaną liczbę o 1

### ISSUE THREAD

**Issue by krasickiPawel** [ZIWG-PBMMT/frontend#16]
stworzyć komponenty:
- [ ] przycisk
- [ ] coś na czym można zapisać i wyświetlić liczbę

- [ ] zaprogramować je tak, żeby po kliknięciu przycisku wyświetlana liczba zwiększyła się o 1

każdy z nas powinien się tego nauczyć

**Comment by julianjunior07** [comment]
no zrobiłem taki programik wg poradnika, coś już tam powoli zaczynam rozumieć
